### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by corysimmons** [Landerson352/jeet-less#1]
Wow! We've been dying for a port to LESS. Does this work yet?

**Comment by Landerson352** [comment]
Eh, kinda... :) I need to add some tests in for the full set of options. The basics do seem to work so far. Sorry for the weak answer, this is sort of a pet project of mine I started during a day off work.

**Comment by corysimmons** [comment]
The basics work? Can you write up a little demo?

**Comment by Landerson352** [comment]
Sure thing - there is a little demo in the "tests" folder if you're curious. It covers a few scenarios like columns sizing, offsets and cycling. I'd like to see a test of every aspect of Jeet functionality, but hopefully that can tide you over for a bit.

**Comment by corysimmons** [comment]
Wow this is pretty amazing. Interested in working on https://github.com/corysimmons/jeet.js ?

**Comment by Landerson352** [comment]
That's pretty neat. Does it need to run on an interval, or is that just so you can alter the values on the fly?

**Comment by corysimmons** [comment]
I'll probably add a throttle in for responsiveness when I get the rest of it working.
